### ISSUE TITLE
"tput: No value for $TERM and no -T specified" when using SBT

### ISSUE THREAD

**Issue by ruippeixotog** [buildkite/terminal#49]
In all our Buildkite builds using [sbt](https://www.scala-sbt.org) (the build tool for Scala projects), sbt prints this message many times during the process:

```
tput: No value for $TERM and no -T specified
```

Since I can't reproduce this any any other environment, this may be an issue with the tty used by Buildkite. Do you have any idea of what the problem might be and how can I fix it?

**Comment by toolmantim** [comment]
Sorry you hit this bug! I'm guessing it was related to the things fixed in buildkite/agent#751, which should be available in the next agent release.

**Comment by queimadus** [comment]
Tested this with [v3.1.2](https://github.com/buildkite/agent/blob/master/CHANGELOG.md#v312-2018-05-10) which included the buildkite/agent#751 fix and the problem persists.
